custom_scara:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 150.0, i: 0.01, d: 80.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 150.0, i: 0.01, d: 80.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 150.0, i: 0.01, d: 80.0}

  
      # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint1
    pid: {p: 100.0, i: -0.01, d: 0}

  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint4
    pid: {p: 20.0, i: -0.01, d: 0}

  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint6
    pid: {p: 0.0, i: 0, d: 0}